name       : perl-test-fatal
version    : '0.017'
release    : 7
source     :
    - https://cpan.metacpan.org/authors/id/R/RJ/RJBS/Test-Fatal-0.017.tar.gz : 37dfffdafb84b762efe96b02fb2aa41f37026c73e6b83590db76229697f3c4a6
homepage   : https://metacpan.org/pod/Test::Fatal
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Test::Fatal incredibly simple helpers for testing code with exceptions
description: |
    Test::Fatal is an alternative to the popular Test::Exception. It does much less, but should allow greater flexibility in testing exception-throwing code with about the same amount of typing.
builddeps  :
    - perl-try-tiny
rundeps    :
    - perl-try-tiny
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
