name       : perl-test-fatal
version    : '0.016'
release    : 6
source     :
    - https://cpan.metacpan.org/authors/id/R/RJ/RJBS/Test-Fatal-0.016.tar.gz : 7283d430f2ba2030b8cd979ae3039d3f1b2ec3dde1a11ca6ae09f992a66f788f
homepage   : https://metacpan.org/pod/Test::Fatal
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Test::Fatal incredibly simple helpers for testing code with exceptions
description: |
    Test::Fatal is an alternative to the popular Test::Exception. It does much less, but should allow greater flexibility in testing exception-throwing code with about the same amount of typing.
builddeps  :
    - perl-try-tiny
rundeps    :
    - perl-try-tiny
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
