name       : perl-test-fatal
version    : 0.014
release    : 5
source     :
    - http://search.cpan.org/CPAN/authors/id/R/RJ/RJBS/Test-Fatal-0.014.tar.gz : bcdcef5c7b2790a187ebca810b0a08221a63256062cfab3c3b98685d91d1cbb0
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Test::Fatal incredibly simple helpers for testing code with exceptions
description: |
    Test::Fatal incredibly simple helpers for testing code with exceptions.
builddeps  :
    - perl-try-tiny
rundeps    :
    - perl-try-tiny
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
